apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blast-postgres-data
selector:
  app: quarkus-blast-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
