apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: blast-quarkus
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-quarkus-tenant/quarkus-blast/blast-quarkus@sha256:9e5a32717cf45076c230328982b63d47e9e50bb0c28106a6d1e084fd4f1c067b
        name: blast-quarkus
        resources: {}
status: {}
