apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: blast-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: blast-quarkus
    app.kubernetes.io/part-of: quarkus-blast
  name: blast-quarkusgiz3
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: blast-quarkus
    weight: null
status: {}
