apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: blast-postgres
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: blast-postgres
    app.kubernetes.io/part-of: quarkus-blast
  name: blast-postgresdqug
spec:
  port:
    targetPort: 5432
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: blast-postgres
    weight: 100
status: {}
