apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: blast-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: blast-quarkus
    app.kubernetes.io/part-of: quarkus-blast
  name: blast-quarkus
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: blast-quarkus
status:
  loadBalancer: {}
